apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "volsync-addon-controller.fullname" . }}
  labels:
    app: {{ template "volsync-addon-controller.name" . }}
    chart: {{ template "volsync-addon-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "volsync-addon-controller.name" . }}
    helm.sh/chart: {{ template "volsync-addon-controller.chart" . }}
    component: volsync-addon-controller-serviceaccount