# Copyright Contributors to the Open Cluster Management project
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
