# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Copyright Contributors to the Open Cluster Management project
---

apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster_service: 'true'
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Release.Name }}-tls-secret
  name: {{ .Values.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.oauth_proxy.httpsPort }}
    - name: ingress
      port: {{ .Values.httpsPort }}
      targetPort: {{ .Values.httpsPort }}
  selector:
    k8s-app: {{ .Release.Name }}
