# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:{{ .Values.klusterletAddonController.name }}-v2
  labels:
    app: {{ .Values.klusterletAddonController.name }}-v2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.klusterletAddonController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.klusterletAddonController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
subjects:
- kind: ServiceAccount
  name: {{ .Values.klusterletAddonController.name }}-v2
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Release.Name }}:{{ .Values.klusterletAddonController.name }}-v2
  apiGroup: rbac.authorization.k8s.io
