# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.klusterletAddonController.name }}-v2
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.klusterletAddonController.name }}-v2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.klusterletAddonController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.klusterletAddonController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
