# Copyright Contributors to the Open Cluster Management project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "clusterbackup.fullname" . }}-clusterbackup
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "clusterbackup.name" . }}    
    chart: {{ template "clusterbackup.chart" . }}
    component: "clusterbackup"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "clusterbackup.name" . }}
    helm.sh/chart: {{ template "clusterbackup.chart" . }}
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "clusterbackup.name" . }}
      component: "clusterbackup"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "clusterbackup.name" . }}
        ocm-antiaffinity-selector: "clusterbackup"
        component: "clusterbackup"
        release: {{ .Release.Name }}
        chart: {{ template "clusterbackup.chart" . }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ template "clusterbackup.name" . }}
        helm.sh/chart: {{ template "clusterbackup.chart" . }}  
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ template "clusterbackup.fullname" . }}
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                {{- toYaml .Values.arch | nindent 18 }}
        {{- with .Values.affinity.podAntiAffinity }}
        podAntiAffinity:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.hubconfig.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: cluster-backup
        image: {{ .Values.global.imageOverrides.cluster_backup_controller }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        resources:
        {{- toYaml .Values.clusterbackup.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecret }}
      {{- end }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
