# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:clusterrole
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "clusterbackup.name" . }}
    chart: {{ template "clusterbackup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "clusterbackup.name" . }}
    helm.sh/chart: {{ template "clusterbackup.chart" . }}
    component: clusterrole

rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
