# Copyright Contributors to the Open Cluster Management project
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  labels:
    app: {{ template "clusterbackup.name" . }}
    chart: {{ template "clusterbackup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "clusterbackup.name" . }}
    helm.sh/chart: {{ template "clusterbackup.chart" . }}
    velero.io/exclude-from-backup: "true"
    component: policy
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-4 Backups of information are conducted maintained and tested
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/source: system
  name: {{ .Values.BackupRestorePolicyName }}
  namespace: {{ .Release.Namespace }}
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    app: {{ template "clusterbackup.name" . }}
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: Running
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oadp-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  annotations:
                    repository: https://github.com/openshift/oadp-operator
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: Running
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: velero-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    app.kubernetes.io/name: velero
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: Running
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: data-protection-application-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: oadp.openshift.io/v1alpha1
                kind: DataProtectionApplication
                metadata:
                  namespace: {{ .Release.Namespace }}
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: backup-storage-location-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: BackupStorageLocation
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: Available
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: backup-schedule-cron-enabled
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  labels:
                    velero.io/schedule-name: acm-validation-policy-schedule
                  namespace: {{ .Release.Namespace }}
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-managed-clusters-schedule-backups-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: {{ .Release.Namespace }}
                  labels:
                    velero.io/schedule-name: acm-managed-clusters-schedule
                status:
                  phase: Completed
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-resources-schedule-backups-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: {{ .Release.Namespace }}
                  labels:
                    velero.io/schedule-name: acm-resources-schedule
                status:
                  phase: Completed
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-in-progress-report
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: InProgress                                                            
          remediationAction: inform
          severity: medium
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-clusters-collision-report
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: {{ .Values.ClusterCollisionPhase }}                                                            
          remediationAction: inform
          severity: high   
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-phase-validation
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: FailedValidation 
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: Failed 
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: ""
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Restore
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: ""
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Restore
                metadata:
                  namespace: {{ .Release.Namespace }}
                status:
                  phase: Error                                                       
          remediationAction: inform
          severity: high                                                                        
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ .Values.BackupRestorePolicyName }}
  namespace: {{ .Release.Namespace }}
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: {{ .Values.BackupRestorePolicyName }}
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: {{ .Values.BackupRestorePolicyName }}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ .Values.BackupRestorePolicyName }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
