# Copyright Contributors to the Open Cluster Management project

# pre hook used to install the OADP Operator, using the {{ .Values.oadpOperator.namespace }} namespace
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.oadpOperator.name }}-subscription
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": delete
spec:
  channel: {{ .Values.oadpOperator.channel }}
  startingCSV: {{ .Values.oadpOperator.startingCSV }}
  config:
    resources: {}
{{- with .Values.hubconfig.nodeSelector }}
    nodeSelector:
{{ toYaml . | indent 6 }}
{{- end }}
{{- with .Values.hubconfig.tolerations }}
    tolerations:
{{- toYaml . | nindent 6 }}
{{- end }}
    env:
    {{- if .Values.hubconfig.proxyConfigs }}
    - name: HTTP_PROXY
      value: {{ .Values.hubconfig.proxyConfigs.HTTP_PROXY }}
    - name: HTTPS_PROXY
      value: {{ .Values.hubconfig.proxyConfigs.HTTPS_PROXY }}
    - name: NO_PROXY
      value: {{ .Values.hubconfig.proxyConfigs.NO_PROXY }}
    {{- end }}
  installPlanApproval: {{ .Values.oadpOperator.installPlanApproval}}
  name: {{ .Values.oadpOperator.name }}
  source: {{ .Values.oadpOperator.source }}
  sourceNamespace: {{ .Values.oadpOperator.sourceNamespace }}