# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:readonly-clusterimagesets
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Release.Name }}:aggregate-clusterimagesets-readonly
  apiGroup: rbac.authorization.k8s.io
