# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project


insights:
  name:
    type: string
  fullname:
    type: string
  __metadata:
    label: "Multicloud Insights Client"
    description: "Configuration for Multicloud Manager Insights Client"
  insights-client:
    resources:
      requests:
        memory:
          type: "string"
        cpu:
          type: "string"
      limits:
        memory:
          type: "string"
        cpu:
          type: "string"

global:
  arch:
    type: options
  certificateAuthority:
    issuer:
      __metadata:
        label: "Certificate Authority Issuer"
        description: "CA to sign the certificates for the insights services"
        type: string
    kind:
      __metadata:
        label: "Certificate Issuer Kind"
        description: "Kind of certificate issuer (ClusterIssuer or Issuer)"
        type: string
  __metadata:
    label: "Global Settings for Insights"
    description: "Global Settings for Insights Chart Deployment"
  pullSecret:
    __metadata:
      label: "Docker Registry Authentication"
      description: "Secret of Docker Authentication"
      type: "string"
      immutable: false
      required: false
  pullPolicy:
    __metadata:
      label: "Image Pull Policy"
      description:  "Global image pullPolicy for all components"
      type: "string"
      required: false
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
