# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: grc-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grc.name" . }}
    chart: {{ template "grc.chart" . }}
    component: "ocm-grc-sa"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "grc.name" . }}
    helm.sh/chart: {{ template "grc.chart" . }}