# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: insights-metrics-certs
  name: insights-metrics
  labels:
    insights-app: {{ .Values.insights.name }}
    app: {{ template "insights.name" . }}
    chart: {{ template "insights.chart" . }}
    component: insights-metrics
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8443 
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: {{ template "insights.name" . }}
    component: "insights-metrics"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  sessionAffinity: ClientIP
