apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-08-11T20:04:39.386479737Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5c6a2a81792e17bb8eda99d123f3332afae089c53dc92389274f750561ef7912
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.10.tgz
    version: 2.1.10
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-08-11T20:04:39.387577796Z"
    description: Service for issuing and managing certificates.
    digest: 3db650ae37c93a1714262bfc33a044d6b56aa24d1ae6a9a945535727eb1ca1a2
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.10.tgz
    version: 2.1.10
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-08-11T20:04:39.389027904Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 7e3b469450e17bd0535817c35656c6d6d79f7d09b12393a236fc4c15581c72c7
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.10.tgz
    version: 2.1.10
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-08-11T20:04:39.389838033Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 692f0bf3a810b48769ecfc8c078b14d2cf77d9c46304daec5431944890f94df3
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.10.tgz
    version: 2.1.10
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-08-11T20:04:39.390521907Z"
    description: Helm chart for Open Cluster Management console UI
    digest: cf3b245784fd962ea2f9016895a7ad842d57046709882b0b5ea6d3160cb5ed69
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.10.tgz
    version: 2.1.10
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-08-11T20:04:39.390962784Z"
    description: helm chart for multicloud grc
    digest: 0a16f4d6cf5b3b8de7077848e7e32c49bb8ec783e71c0a1f4c46bd7ebe67668b
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.10.tgz
    version: 2.1.10
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-08-11T20:04:39.392850475Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: fec895459807fc268aeab0fb1321d40416ecc57d8041a02e103207845f3c5465
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.10.tgz
    version: 2.1.10
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-08-11T20:04:39.394891714Z"
    description: Multi Cloud control plane ingress controller
    digest: 51778e81cb49e5f07fca3cd8312c8de899e43a4fcaa21840b908fe3eb8872edb
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.10.tgz
    version: 2.1.10
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-08-11T20:04:39.396196979Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: fe99c9242adec52243625736f8ece09344a048ddc580585101b2840d5e92e9a1
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.10.tgz
    version: 2.1.10
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-08-11T20:04:39.397249759Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 06589b05492dd689decbc7f41b13ab2add352d08bcc68807ec0d8fc5ad69b9c8
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.10.tgz
    version: 2.1.10
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-08-11T20:04:39.397713452Z"
    description: helm chart for multicloud topology
    digest: 68391f9388a69a6147e06fc3d45001d19a3f70963fe0a539dd1fb9e8ad7f6f94
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.10.tgz
    version: 2.1.10
generated: "2021-08-11T20:04:39.385792035Z"
